[workspace]
members = [
    "company_data_store",
    "company_scraper",
    "job_applier",
]

[package]
name = "search_and_apply"

[dependencies]
company_data_store = { path = "company_data_store" }
company_scraper = { path = "company_scraper" }
job_applier = { path = "job_applier" }