[package]
name = "company_data_store"
version = "0.1.0"
edition = "2021"

[dependencies]
company_common = { path = "../company_common" }
serde_json = "1.0.117"
serde = { version = "1.0.203", features = ["derive"] }
tokio-postgres = "0.7.11"
dotenvy = "0.15.7"
anyhow = "1.0.86"
tokio = "1.37.0"