[package]
name = "company_data_store"

[dependencies]
company_common = { path = "../company_common" }
serde_json = "1.0.117"
serde = { version = "1.0.203", features = ["derive"] }
postgres = { version = "0.19.7"}
dotenvy = "0.15.7"
anyhow = "1.0.86"